-- Create users table
create table public.users (
    id uuid default auth.uid() primary key,
    email text unique,
    status text check (status in ('active', 'inactive', 'suspended')) default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create deliveries table
create table public.deliveries (
    id bigint generated by default as identity primary key,
    user_id uuid references public.users(id),
    status text check (status in ('pending', 'in_transit', 'completed', 'cancelled')) default 'pending',
    location text not null,
    description text,
    completed_at timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create payments table
create table public.payments (
    id bigint generated by default as identity primary key,
    delivery_id bigint references public.deliveries(id),
    amount decimal(10,2) not null,
    status text check (status in ('pending', 'completed', 'failed')) default 'pending',
    payment_method text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create RLS policies
alter table public.users enable row level security;
alter table public.deliveries enable row level security;
alter table public.payments enable row level security;

-- Users policies
create policy "Users can view their own data" on public.users
    for select using (auth.uid() = id);

-- Deliveries policies
create policy "Users can view their own deliveries" on public.deliveries
    for select using (auth.uid() = user_id);

create policy "Users can create their own deliveries" on public.deliveries
    for insert with check (auth.uid() = user_id);

-- Payments policies
create policy "Users can view their own payments" on public.payments
    for select using (
        auth.uid() in (
            select user_id from public.deliveries where id = delivery_id
        )
    );

-- Create indexes
create index idx_users_status on public.users(status);
create index idx_deliveries_status on public.deliveries(status);
create index idx_deliveries_completed_at on public.deliveries(completed_at);
create index idx_payments_status on public.payments(status); 